"""Markdown output formatting."""

from datetime import datetime
from slugify import slugify

from .config import SESSION_TYPES


def slugify_session_name(name: str) -> str:
    """Hebrew-safe slugify: transliterate to ASCII, lowercase, hyphens only."""
    result = slugify(name, max_length=50)
    return result or "session"


def generate_folder_name(
    session_type: str,
    session_name: str | None = None,
    timestamp: datetime | None = None,
) -> str:
    """Generate folder name: YYYY-MM-DD_HH-MM_session-name."""
    ts = timestamp or datetime.now()
    date_part = ts.strftime("%Y-%m-%d_%H-%M")

    if session_name:
        name_part = slugify_session_name(session_name)
    else:
        name_part = session_type

    return f"{date_part}_{name_part}"


def format_duration(seconds: float) -> str:
    """Format seconds as HH:MM:SS or MM:SS."""
    seconds = int(seconds)
    h, remainder = divmod(seconds, 3600)
    m, s = divmod(remainder, 60)
    if h > 0:
        return f"{h:02d}:{m:02d}:{s:02d}"
    return f"{m:02d}:{s:02d}"


def format_transcript_md(
    transcript_text: str,
    original_name: str,
    session_type: str,
    speakers: str,
    language: str,
    original_duration: float,
    trimmed_duration: float,
    silence_removed: float,
    timestamp: datetime,
) -> str:
    """Format the raw transcript as a markdown document with metadata."""
    type_info = SESSION_TYPES.get(session_type, SESSION_TYPES["other"])
    type_label = type_info["he"] if language == "he" else type_info["en"]
    lang_label = "עברית" if language == "he" else "English"

    return f"""# {original_name}

| Field | Value |
|-------|-------|
| **Date** | {timestamp.strftime("%Y-%m-%d %H:%M")} |
| **Session Type** | {type_info["emoji"]} {type_label} |
| **Speakers** | {speakers or "—"} |
| **Language** | {lang_label} |
| **Original Duration** | {format_duration(original_duration)} |
| **Trimmed Duration** | {format_duration(trimmed_duration)} |
| **Silence Removed** | {format_duration(silence_removed)} |

---

{transcript_text}
"""


def format_analysis_md(
    analysis_text: str,
    summary: str,
    session_type: str,
    speakers: str,
    timestamp: datetime,
) -> str:
    """Format the analysis output as a markdown document."""
    type_info = SESSION_TYPES.get(session_type, SESSION_TYPES["other"])

    return f"""# {type_info["emoji"]} Analysis — {timestamp.strftime("%Y-%m-%d %H:%M")}

> **Summary:** {summary}

---

{analysis_text}

---

*Generated by Zumo*
"""
